# Generated by Django 3.1.7 on 2021-05-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statu',
            new_name='status',
        ),
    ]
